-- Truncate table commands
TRUNCATE TABLE CLASSIC_DB.GOLD.DIM_CUSTOMER;
TRUNCATE TABLE CLASSIC_DB.GOLD.DIM_DATE;
TRUNCATE TABLE CLASSIC_DB.GOLD.DIM_PRIORITY;
TRUNCATE TABLE CLASSIC_DB.GOLD.FACT_ORDER;

TRUNCATE TABLE CLASSIC_DB.SILVER.CUSTOMER_CURATED;
TRUNCATE TABLE CLASSIC_DB.SILVER.ORDER_CURATED;

TRUNCATE TABLE CLASSIC_DB.BRONZE.CUSTOMER_RAW;
TRUNCATE TABLE CLASSIC_DB.BRONZE.ORDER_RAW;